### ISSUE TITLE
ACF Pro, no scroll bars

### ISSUE THREAD

**Issue by aldingamedia** [admin-2020/Admin-2020-Theme#26] opened 2020-05-25 03:48 UTC
The ACF Pro doesn't seem to scroll when expanding a large list of field rows. It becomes cut off after about 15 rows.

I do have Oxygen Builder active so I am not sure if it is Oxygen covering it.

![image](https://user-images.githubusercontent.com/65576355/82776446-2912e100-9e8a-11ea-9940-4d6f37e7160f.png)

**Comment by aldingamedia** [comment] 2020-05-26 02:16
I have installed version 1.1.9 and this problem still exists.

**Comment by admin-2020** [comment] 2020-05-26 18:10
Ok, we will look to get this fixed in the next version, I will update here when it's fixed!

**Comment by admin-2020** [comment] 2020-05-27 12:13
Looks like this was caused by CSS style setting a max-height on the container. Will be fixed in version 1.2.0 - In the mean time if you want to fix, either add the below to the admin css or using an admin css plugin:

```
.inside {
  max-height: 20000px !important;
}
```

**Closed as completed** 2020-06-01 10:39 UTC
